### PR TITLE
`windows` crate upgrade

### LINKED ISSUE #39: Build script doesn't work when cross compiling to Windows
The build script doesn't generate bindings unless [running on Windows](https://github.com/ArturKovacs/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/build.rs#L4) which means compiling on a non-Windows platform targeting Windows won't generate the bindings and thus fail building as seen in https://github.com/Jake-Shadle/xwin/issues/10. The build script should use `CARGO_CFG_TARGET_OS` to determine whether it should build the bindings or not.

### PR DESCRIPTION
**Pull request by Byron**
Fix #39 by getting the latest `windows` crate.

It's quite a chore as a lot changed, but let's hope the overall code still works once it compiles.

### CODE REVIEW

**Comment by Byron** [comment]
The remaining 6 errors are a little bit beyond my abilities and level of torture I can take 😅.

**Comment by rgwood** [comment]
FYI I'm working on this. Think I have it mostly figured out, just need to figure out 1 remaining method call and some polish. ETA: a few days from now?

**Comment by ArturKovacs** [comment]
If there's anything specific you need help with, feel free to let me know (I'm the original author of some of this code)

**Comment by rgwood** [comment]
@ArturKovacs Thanks! I've got things compiling but I'm stuck on an unexpected failure at runtime. It's late here but I'll try to put up a draft PR for you to look at tomorrow.

**Comment by Byron** [comment]
Closed in favor of #51 .

**Pull request closed without merging**
