### PR TITLE
Upgrade windows crate from v0.37 to v0.43

### PR DESCRIPTION
**Pull request by rgwood**
Hello it's me from #51 again!

[The `windows` crate](https://github.com/microsoft/windows-rs) has seen a bit more churn recently, and I figured it might be worth proactively upgrading the version used by `trash-rs`.

Functionality-wise this should not change anything. I measured compile times before+after and it seems about 5% faster now.

### CODE REVIEW

**Comment by rgwood** [comment]
There were some unrelated Clippy failures on Linux (probably related to a new Clippy version), fixed.

**Comment by Byron** [comment]
Thanks so much for your help with this! And by the looks of it, the churn is worth it as the code looks more and more idiomatic!

One day, Windows having a native Rust API might actually want to make me write software for it 😅.

**Comment by Byron** [comment]
And [here is the release](https://github.com/Byron/trash-rs/releases/tag/v3.0.0), I made it a major one maybe for the wrong reason. Can different versions of the `windows` crate co-exist?

**Comment by rgwood** [comment]
> Can different versions of the windows crate co-exist?

Yep! Compiling `windows` twice is a bit rough for compile times but it has been working fine in Nushell.

**Pull request merged**
