### PR TITLE
Add BSD compatible implementation of get_mount_points

### LINKED ISSUE #40: Broken dependency resolution on non-Linux unixes
In `Cargo.toml`, `chrono` is declared as a dependency only under Linux:
https://github.com/Byron/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/Cargo.toml#L36-L37

But it is used in the Freedesktop backend without a Linux-only precondition:
https://github.com/Byron/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/src/freedesktop.rs#L18

And the Freedesktop backend is used for any non-macOS unix target:
https://github.com/Byron/trash-rs/blob/3c566ef417350b75e02ea80be51165815014ec74/src/lib.rs#L33-L35

This causes the build to fail when compiled on a non-Linux unix-ish platform like FreeBSD. 

The conditional dependency logic in Cargo.toml needs to match your actual use.

### PR DESCRIPTION
**Pull request by wezm**
This PR adds an implementation of `get_mount_points` for BSD systems. Whilst FreeBSD, NetBSD, OpenBSD all have the `getmntinfo` function, it's only exposed in the `libc` crate for FreeBSD. This means that while the code would in theory work on NetBSD and OpenBSD it currently fails to build with an error about `getmntinfo` and `MNT_WAIT` missing from `libc`.

On FreeBSD it compiles and the tests pass.

Fixes #40

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot for tackling this, it's much appreciated.

It took me some time to properly study the required use of unsafe here and after reading the docs for `getmntinfo` it appears that the data within the array isn't owned (hence not freed), but instead it's stored in a static global object.

This very much reminded me of the 'local-time offset drama' in the `time` crate, as I believe in multi-threaded programs this would possibly lead to out of bounds reads if…

- a thread A is reading the `fs_mounts` slice while… (`time` caused obtaining a pointer to the value of an env-var in libc)
- something is dismounted and… (`time` had another thread change that environment variable, invalidating said pointer)
- another thread B calls `getmntinfo()` again which invalidates the array thread A is traversing (`time` shows UB by accessing a now invalid pointer in libc, which doesn't use the lock around env vars)

If this is indeed an issue, now I wonder if the way `time` solves it by bailing out if `!num_threads::is_single_threaded()` would be appropriate here?

**Comment by wezm** [comment]
That is a keen observation. I had wondered about this too. I didn't put anything in to handle it as the linux implementation suffers the same problem:

> The getmntent() function reads the next line of the filesystem description file from stream and returns a pointer to a structure containing the broken out fields from a line in the file.  The pointer points to a static area of memory which is overwritten by subsequent calls to getmntent().

However, on linux there is `getmntent_r`.

> If this is indeed an issue, now I wonder if the way time solves it by bailing out if !num_threads::is_single_threaded() would be appropriate here?

Anyway I think it probably is an issue for all platforms so yes, some sort of thread restriction probably is a good idea.

**Comment by Byron** [comment]
Thanks for the additional research on linux.

> However, on linux there is getmntent_r.

Even though that would be working I'd have trouble knowing how many struct items to allocate, and how much string-space is going to be needed for that. Simply returning an empty array if there are threads present seems possible, but I don't know how that affects the correctness of the crate.

To me it looks like on FreeBSD, the thread-based protection can be added without changing behaviour as it didn't work there before. And to add such protection on linux, one would either figure out correct usage of `getmntent_r` or risk breaking existing programs with a 'fix' that alters behavior.

Now that the potential UB is known I guess the correct way of dealing with it is to push a fix, and since it's breaking, make that  major release while yanking all existing releases with linux support.

What do you think?

**Comment by Byron** [comment]
I added the UB protection to the FreeBSD version merged it to master (after failing to push into this PR), maybe you could have another look to see it's still working.

Also CC @ArturKovacs to see how to deal with the outstanding fix on linux.
Thanks everyone.

**Comment by ArturKovacs** [comment]
I did not realize this issue existed, but yeah this seems relatively serious.

My opinion is that we should use `getmntent_r` on Linux (seems like it needs to be added to the libc crate). And on BSD, the most sensible thing is probably to log an `error!` if there are multiple threads and immediately return with an empty array or an `Error::Unknown`.

**Comment by Byron** [comment]
Thanks for chiming in.

On FreeBSD, what's the preferred way of dealing with it? Return an error, or log and return an empty array?

And for `getmntent_r`, would you have the experience to tackle this? I don't feel too comfortable with doing it and believe I add more UB than I remove 😅.

**Comment by wezm** [comment]
Could a static mutex be used to prevent more than one thread calling the function—the second and subsequent calls would block until the one with the lock finished. Using something like this:

```rust
lazy_static! {
    pub static ref LOCK: Mutex<()> = Mutex::new(());
}
```

**Comment by Byron** [comment]
It would prevent issues if multiple threads call into the `trash` crate, but won't help if multiple threads call into the `getmnt…` functions directly.

When writing this I feel like nitpicking as a mutex probably reduces the likelihood of issues considerably already, especially given how unlikely mountpoints changing at the same time probably is. But I guess to be a good citizen in Rust zero chance of UB is the goaI.

If a small chance of UB is acceptable though, I'd certainly prefer that on FreeBSD than bailing out if there are multiple threads.

**Pull request merged**
